/* ---------- PHOTOS ---------- */
function viewPhotos(){
  var P=PHOTO_LIB,up=state.photos.uploaded,miss=state.photos.showMissing;
  var without=P.total-P.withPhoto;
  var head=pageHead({title:"Add Your <em>Photos</em>",sub:"Drop in everything you have. Benu sorts it, matches each dish to its best shot, and tells you exactly what is missing. Your camera roll is fine."});
  var body;
  if(!up){
    body=`<div class="dropzone" data-act="photoUpload" role="button" tabindex="0" style="width:100%"><div style="margin-bottom:14px">${icon("image",{size:46,color:"var(--mint-600)",stroke:1.3})}</div><div style="font-size:18px;font-weight:600">Drop a folder of photos, or <span style="color:var(--mint-600)">Browse</span></div><div style="color:var(--soft);font-size:13px;margin-top:6px">JPG, PNG or HEIC · as many as you like</div></div><div class="row gap-3 wrap" style="margin-top:16px;justify-content:center"><button class="btn btn-soft btn-sm" data-act="photoUpload">${icon("image",{size:16,color:"var(--mint-900)"})} Import From Instagram</button><button class="btn btn-soft btn-sm" data-act="photoUpload">${icon("locations",{size:16,color:"var(--mint-900)"})} Import From Google</button></div><div style="margin-top:20px">${aiNote("Benu auto sorts food, interior, exterior and team shots, then matches the food photos to your menu items by name. You approve every match before anything goes live.","sparkle")}</div>`;
  } else {
    var cats=[{label:"Food",n:P.counts.food,ic:"catering"},{label:"Interior",n:P.counts.interior,ic:"home"},{label:"Exterior",n:P.counts.exterior,ic:"locations"},{label:"Team",n:P.counts.team,ic:"users"}];
    var catCards=cats.map(function(c){return `<div style="flex:1 1 150px;background:var(--raised);border-radius:14px;padding:16px"><div class="row gap-3"><div style="width:42px;height:42px;border-radius:11px;background:var(--surface);border:1px solid var(--border);display:grid;place-items:center;flex-shrink:0">${icon(c.ic,{size:20,color:"var(--mint-700)"})}</div><div><div style="font-family:var(--serif);font-size:26px;font-weight:600;line-height:1.05">${c.n}</div><div class="metalabel" style="color:var(--soft)">${c.label}</div></div></div></div>`;}).join("");
    var pct=Math.round(P.withPhoto/P.total*100);
    var summary=`<div class="card" style="padding:18px 20px"><div class="row spread" style="gap:14px;flex-wrap:wrap"><div class="row gap-3" style="min-width:0"><div style="width:42px;height:42px;border-radius:11px;background:var(--mint-900);display:grid;place-items:center;flex-shrink:0">${icon("check",{size:20,color:"#CBE0A8",stroke:2.4})}</div><div style="min-width:0"><div style="font-size:19px;font-weight:600">${P.withPhoto} of ${P.total} dishes have a photo</div><div style="font-size:13.5px;color:var(--muted);margin-top:2px">${without} still need one. A clean card stands in until you add it.</div></div></div><button class="btn btn-soft btn-sm" data-act="photoMissing">${miss?"Show All Matches":"See The "+without+" Without"}</button></div><div style="height:8px;border-radius:9px;background:var(--outer);overflow:hidden;margin-top:14px"><div style="height:100%;width:${pct}%;background:var(--mint-600)"></div></div></div>`;
    var shown=miss?P.dishes.filter(function(d){return !d.has;}):P.dishes;
    var rows=shown.map(function(d){
      var thumb=d.has?`<div style="width:46px;height:46px;border-radius:10px;flex-shrink:0;background:linear-gradient(135deg,var(--mint-300),var(--mint-100));display:grid;place-items:center">${icon("image",{size:18,color:"var(--mint-900)"})}</div>`:`<div style="width:46px;height:46px;border-radius:10px;flex-shrink:0;border:1.5px dashed var(--border-strong);display:grid;place-items:center">${icon("image",{size:18,color:"var(--soft)"})}</div>`;
      var badge=d.has?`<span class="st st-ok" style="font-size:11px;padding:6px 11px">${icon("check",{size:12,stroke:2.6})} Photo</span>`:`<span class="st st-warn" style="font-size:11px;padding:6px 11px">${icon("alert",{size:12})} No photo</span>`;
      return `<div class="row spread" style="background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:10px 14px;gap:12px"><div class="row gap-3" style="min-width:0">${thumb}<div style="min-width:0"><div style="font-size:15.5px;font-weight:600">${d.name}</div><div class="metalabel" style="color:var(--soft)">${d.section}</div></div></div>${badge}</div>`;
    }).join("");
    var moreNote=miss&&without>shown.length?`<div class="row center" style="border:1px dashed var(--border-strong);border-radius:12px;padding:11px;font-size:13px;color:var(--muted)">And ${without-shown.length} more waiting on a photo</div>`:"";
    body=`<div class="row gap-3 wrap" style="margin-bottom:18px">${catCards}</div>${summary}<div class="row spread" style="margin:24px 2px 12px;flex-wrap:wrap;gap:8px"><span class="metalabel" style="color:var(--muted)">${miss?"Dishes Without A Photo":"Auto Matched To Your Menu"}</span><span class="row gap-2" style="font-size:12.5px;color:var(--soft)">${icon("sparkle",{size:12,color:"var(--mint-600)"})} You approve every match</span></div><div class="col gap-2">${rows}${moreNote}</div>`;
  }
  var foot=`<button class="btn btn-secondary" data-act="back">${icon("arrowL",{size:18})} Back</button><button class="btn btn-primary btn-lg" data-act="next">${up?"Looks great, continue":"Continue"} ${icon("arrowR",{size:18,color:"#fff"})}</button>`;
  return screenWrap(`${head}${body}`)+footerBar(foot);
}
