/* ---------- SCREEN 9: ALLERGY ---------- */
function viewAllergy(){
  var items=state.allergy.items;
  var counts={suggested:0,review:0,verified:0};
  items.forEach(function(i){counts[i.state]++;});
  var legend=Object.keys(allergyState).map(function(k){var v=allergyState[k];return `<div class="row gap-2" style="background:var(--surface);border:1px solid var(--border);border-radius:999px;padding:7px 14px"><span class="dot" style="background:${v.dot}"></span><span style="font-size:13px;font-weight:500">${v.label}</span><span class="metalabel" style="color:var(--soft)">${counts[k]}</span></div>`;}).join("");
  var cards=items.map(function(it,idx){
    var s=allergyState[it.state];
    var ings=it.ingredients.map(function(g){return `<span class="chip" style="background:var(--raised);color:var(--text);font-weight:500;font-size:12px">${g}</span>`;}).join("");
    var tags=it.tags.map(function(tg){return `<span class="chip" style="background:${tg.warn?"var(--danger-bg)":tg.q?"var(--warn-bg)":"var(--ok-bg)"};color:${tg.warn?"var(--danger)":tg.q?"var(--warn)":"var(--ok)"};font-weight:500;font-size:12px">${tg.warn?icon("alert",{size:11,color:"var(--danger)"}):""}${tg.t}</span>`;}).join("");
    var action=it.state==="verified"
      ?`<button class="btn btn-secondary btn-sm" style="width:100%" data-act="aunverify" data-i="${idx}">${icon("edit",{size:14})} Edit and re-verify</button>`
      :`<div class="row gap-2"><button class="btn btn-secondary btn-sm grow">${icon("edit",{size:14})} Edit</button><button class="btn btn-primary btn-sm grow" data-act="averify" data-i="${idx}">${icon("shield",{size:14,color:"#fff"})} Verify as correct</button></div>`;
    return `<div class="card" style="padding:0;overflow:hidden;border-color:${it.state==="verified"?"var(--mint-400)":it.state==="review"?"#EBD3A0":"var(--border)"}"><div class="row spread" style="padding:15px 18px;border-bottom:1px solid var(--border);background:${it.state==="verified"?"var(--mint-50)":"var(--surface)"}"><div><div style="font-family:var(--serif);font-size:21px;font-weight:600">${it.name}</div><div class="metalabel" style="margin-top:2px">${it.section}</div></div><span class="st ${s.cls}">${icon(s.icon,{size:11,color:s.dot})} ${s.label}</span></div><div style="padding:18px"><div class="metalabel" style="margin-bottom:8px">Ingredients · AI suggested</div><div class="row wrap gap-2" style="margin-bottom:16px">${ings}<button class="chip" style="background:transparent;border:1px dashed var(--border-strong);color:var(--muted);cursor:pointer;font-size:12px">${icon("upload",{size:11})} Add</button></div><div class="metalabel" style="margin-bottom:8px">Dietary and allergens</div><div class="row wrap gap-2" style="margin-bottom:18px">${tags}</div>${action}</div></div>`;
  }).join("");
  var banner=`<div class="row gap-3" style="background:var(--mint-900);border-radius:16px;padding:16px 20px;color:#EDF3E0;align-items:flex-start">${icon("shield",{size:20,color:"#CBE0A8",style:"flex-shrink:0;margin-top:1px"})}<div style="font-size:14px;line-height:1.55"><strong style="color:#fff">Safety first.</strong> AI suggestions are a starting point, not a guarantee. Allergy tags only show to guests once a person from your team marks them <em style="font-family:var(--serif)">verified</em>.</div></div>`;
  var inner=`${pageHead({title:"Ingredients And <em>Allergies</em>",sub:"No rush on this one, so come back whenever you have a quiet moment. Benu suggests ingredients and dietary tags from your menu, and your team gives the final say before guests ever see an allergy label."})}<div style="margin-bottom:22px">${banner}</div><div class="row gap-3 wrap" style="margin-bottom:20px">${legend}</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px" class="alg-grid">${cards}</div>`;
  var foot=`<button class="btn btn-secondary" data-act="toPublish">${icon("arrowL",{size:18})} Back to publish</button><div class="row gap-4"><span class="metalabel" style="color:var(--muted)">${counts.verified}/${items.length} verified by your team</span><button class="btn btn-primary btn-lg">Save and finish later</button></div>`;
  return screenWrap(inner)+footerBar(foot);
}
