/* ---------- SCREEN 8: PUBLISH ---------- */
function viewPublish(){
  var checks=state.publish.checks,published=state.publish.published;
  var reqItems=CHECKLIST.filter(function(c){return c.req;});
  var reqDone=reqItems.filter(function(c){return checks[c.id];}).length;
  var canPublish=reqItems.every(function(c){return checks[c.id];});
  var built=BUILT.map(function(b){return `<div class="card row spread" style="padding:14px 16px"><div class="row gap-3"><div style="width:38px;height:38px;border-radius:10px;background:var(--mint-50);display:grid;place-items:center">${icon(b.icon,{size:18,color:"var(--mint-700)"})}</div><div><div style="font-size:15px;font-weight:600">${b.name}</div><div class="metalabel" style="margin-top:2px">${b.detail}</div></div></div>${b.ok?`<span class="st st-ok">${icon("check",{size:11,stroke:2.6})} Ready</span>`:`<span class="st st-warn">1 to fix</span>`}</div>`;}).join("");
  var list=CHECKLIST.map(function(c){var done=checks[c.id];return `<button data-act="pcheck" data-id="${c.id}" class="row gap-3" style="width:100%;text-align:left;border:none;background:transparent;cursor:pointer;padding:13px 12px;border-radius:12px">${tick(done)}<div class="grow"><div style="font-size:14.5px;font-weight:500;color:${done?"var(--muted)":"var(--text)"};text-decoration:${done?"line-through":"none"}">${c.label}</div></div>${c.req?`<span class="st st-danger" style="visibility:${done?"hidden":"visible"}">Required</span>`:`<span class="st st-neutral">Optional</span>`}</button>`;}).join("");
  var warn=!canPublish?`<div style="margin-top:14px"><div class="row gap-3" style="background:var(--warn-bg);border:1px solid #EBD3A0;border-radius:14px;padding:13px 16px;align-items:flex-start">${icon("alert",{size:17,color:"var(--warn)",style:"flex-shrink:0;margin-top:1px"})}<div style="font-size:13.5px;color:#7a5a18;line-height:1.5"><strong>${reqItems.length-reqDone} required ${reqItems.length-reqDone===1?"item":"items"} left.</strong> The publish button unlocks once these are done, so a wrong price or an unconfirmed package never slips out by accident.</div></div></div>`:"";
  var inner=`${pageHead({title:published?"You’re <em>Live</em>":"Ready To Go <em>Live</em>",sub:published?"Your menu, ordering and homepage are now published. Share your QR codes and start taking orders.":"Here’s everything Benu built. Tick off the must-do items below and the publish button is yours."})}<div style="display:grid;grid-template-columns:1.1fr 1fr;gap:22px" class="pub-grid"><div><div class="metalabel" style="margin-bottom:12px">What Benu built</div><div class="col gap-2">${built}</div></div><div><div class="metalabel" style="margin-bottom:12px">Before you publish</div><div class="card" style="padding:8px">${list}</div>${warn}<div style="margin-top:16px" class="row spread"><span class="metalabel" style="color:var(--muted)">${reqDone}/${reqItems.length} required done</span><button class="btn btn-primary btn-lg" ${(!canPublish||published)?"disabled":""} data-act="publish">${published?`${icon("check",{size:18,color:"#fff",stroke:2.4})} Published`:`${icon("sparkle",{size:17,color:"#fff"})} Publish my restaurant`}</button></div></div></div>`;
  var foot=`<button class="btn btn-secondary" data-act="back">${icon("arrowL",{size:18})} Back</button><button class="btn btn-ghost" data-act="later">Preview The Allergy Setup Screen ${icon("arrowR",{size:16})}</button>`;
  return screenWrap(inner)+footerBar(foot);
}
